// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2020_2_ExtraSafe/services/board_service/internal/boardStorage (interfaces: TasksStorage)

// Package mock is a generated GoMock package.
package mock

import (
	models "github.com/go-park-mail-ru/2020_2_ExtraSafe/internal/models"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockTasksStorage is a mock of TasksStorage interface
type MockTasksStorage struct {
	ctrl     *gomock.Controller
	recorder *MockTasksStorageMockRecorder
}

// MockTasksStorageMockRecorder is the mock recorder for MockTasksStorage
type MockTasksStorageMockRecorder struct {
	mock *MockTasksStorage
}

// NewMockTasksStorage creates a new mock instance
func NewMockTasksStorage(ctrl *gomock.Controller) *MockTasksStorage {
	mock := &MockTasksStorage{ctrl: ctrl}
	mock.recorder = &MockTasksStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockTasksStorage) EXPECT() *MockTasksStorageMockRecorder {
	return m.recorder
}

// AssignUser mocks base method
func (m *MockTasksStorage) AssignUser(arg0 models.TaskAssigner) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignUser", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignUser indicates an expected call of AssignUser
func (mr *MockTasksStorageMockRecorder) AssignUser(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignUser", reflect.TypeOf((*MockTasksStorage)(nil).AssignUser), arg0)
}

// ChangeTask mocks base method
func (m *MockTasksStorage) ChangeTask(arg0 models.TaskInput) (models.TaskInternal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeTask", arg0)
	ret0, _ := ret[0].(models.TaskInternal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChangeTask indicates an expected call of ChangeTask
func (mr *MockTasksStorageMockRecorder) ChangeTask(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeTask", reflect.TypeOf((*MockTasksStorage)(nil).ChangeTask), arg0)
}

// ChangeTaskOrder mocks base method
func (m *MockTasksStorage) ChangeTaskOrder(arg0 models.TasksOrderInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeTaskOrder", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangeTaskOrder indicates an expected call of ChangeTaskOrder
func (mr *MockTasksStorageMockRecorder) ChangeTaskOrder(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeTaskOrder", reflect.TypeOf((*MockTasksStorage)(nil).ChangeTaskOrder), arg0)
}

// CreateTask mocks base method
func (m *MockTasksStorage) CreateTask(arg0 models.TaskInput) (models.TaskInternalShort, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTask", arg0)
	ret0, _ := ret[0].(models.TaskInternalShort)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTask indicates an expected call of CreateTask
func (mr *MockTasksStorageMockRecorder) CreateTask(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTask", reflect.TypeOf((*MockTasksStorage)(nil).CreateTask), arg0)
}

// DeleteTask mocks base method
func (m *MockTasksStorage) DeleteTask(arg0 models.TaskInput) (models.TaskInternalShort, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTask", arg0)
	ret0, _ := ret[0].(models.TaskInternalShort)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteTask indicates an expected call of DeleteTask
func (mr *MockTasksStorageMockRecorder) DeleteTask(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTask", reflect.TypeOf((*MockTasksStorage)(nil).DeleteTask), arg0)
}

// DismissUser mocks base method
func (m *MockTasksStorage) DismissUser(arg0 models.TaskAssigner) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DismissUser", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DismissUser indicates an expected call of DismissUser
func (mr *MockTasksStorageMockRecorder) DismissUser(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DismissUser", reflect.TypeOf((*MockTasksStorage)(nil).DismissUser), arg0)
}

// GetAssigners mocks base method
func (m *MockTasksStorage) GetAssigners(arg0 models.TaskInput) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAssigners", arg0)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAssigners indicates an expected call of GetAssigners
func (mr *MockTasksStorageMockRecorder) GetAssigners(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAssigners", reflect.TypeOf((*MockTasksStorage)(nil).GetAssigners), arg0)
}

// GetCardIDByTask mocks base method
func (m *MockTasksStorage) GetCardIDByTask(arg0 int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCardIDByTask", arg0)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCardIDByTask indicates an expected call of GetCardIDByTask
func (mr *MockTasksStorageMockRecorder) GetCardIDByTask(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCardIDByTask", reflect.TypeOf((*MockTasksStorage)(nil).GetCardIDByTask), arg0)
}

// GetTaskByID mocks base method
func (m *MockTasksStorage) GetTaskByID(arg0 models.TaskInput) (models.TaskInternal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskByID", arg0)
	ret0, _ := ret[0].(models.TaskInternal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskByID indicates an expected call of GetTaskByID
func (mr *MockTasksStorageMockRecorder) GetTaskByID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskByID", reflect.TypeOf((*MockTasksStorage)(nil).GetTaskByID), arg0)
}

// GetTasksByCard mocks base method
func (m *MockTasksStorage) GetTasksByCard(arg0 models.CardInput) ([]models.TaskInternalShort, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTasksByCard", arg0)
	ret0, _ := ret[0].([]models.TaskInternalShort)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTasksByCard indicates an expected call of GetTasksByCard
func (mr *MockTasksStorageMockRecorder) GetTasksByCard(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTasksByCard", reflect.TypeOf((*MockTasksStorage)(nil).GetTasksByCard), arg0)
}
