// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2020_2_ExtraSafe/internal/services/profile (interfaces: UserStorage)

// Package mock is a generated GoMock package.
package mock

import (
	models "github.com/go-park-mail-ru/2020_2_ExtraSafe/internal/models"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockUserStorage is a mock of UserStorage interface
type MockUserStorage struct {
	ctrl     *gomock.Controller
	recorder *MockUserStorageMockRecorder
}

// MockUserStorageMockRecorder is the mock recorder for MockUserStorage
type MockUserStorageMockRecorder struct {
	mock *MockUserStorage
}

// NewMockUserStorage creates a new mock instance
func NewMockUserStorage(ctrl *gomock.Controller) *MockUserStorage {
	mock := &MockUserStorage{ctrl: ctrl}
	mock.recorder = &MockUserStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUserStorage) EXPECT() *MockUserStorageMockRecorder {
	return m.recorder
}

// ChangeUserAccounts mocks base method
func (m *MockUserStorage) ChangeUserAccounts(arg0 models.UserInputLinks) (models.UserOutside, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeUserAccounts", arg0)
	ret0, _ := ret[0].(models.UserOutside)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChangeUserAccounts indicates an expected call of ChangeUserAccounts
func (mr *MockUserStorageMockRecorder) ChangeUserAccounts(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeUserAccounts", reflect.TypeOf((*MockUserStorage)(nil).ChangeUserAccounts), arg0)
}

// ChangeUserPassword mocks base method
func (m *MockUserStorage) ChangeUserPassword(arg0 models.UserInputPassword) (models.UserOutside, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeUserPassword", arg0)
	ret0, _ := ret[0].(models.UserOutside)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChangeUserPassword indicates an expected call of ChangeUserPassword
func (mr *MockUserStorageMockRecorder) ChangeUserPassword(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeUserPassword", reflect.TypeOf((*MockUserStorage)(nil).ChangeUserPassword), arg0)
}

// ChangeUserProfile mocks base method
func (m *MockUserStorage) ChangeUserProfile(arg0 models.UserInputProfile, arg1 models.UserAvatar) (models.UserOutside, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeUserProfile", arg0, arg1)
	ret0, _ := ret[0].(models.UserOutside)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChangeUserProfile indicates an expected call of ChangeUserProfile
func (mr *MockUserStorageMockRecorder) ChangeUserProfile(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeUserProfile", reflect.TypeOf((*MockUserStorage)(nil).ChangeUserProfile), arg0, arg1)
}

// GetUserAccounts mocks base method
func (m *MockUserStorage) GetUserAccounts(arg0 models.UserInput) (models.UserOutside, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserAccounts", arg0)
	ret0, _ := ret[0].(models.UserOutside)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserAccounts indicates an expected call of GetUserAccounts
func (mr *MockUserStorageMockRecorder) GetUserAccounts(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserAccounts", reflect.TypeOf((*MockUserStorage)(nil).GetUserAccounts), arg0)
}

// GetUserAvatar mocks base method
func (m *MockUserStorage) GetUserAvatar(arg0 models.UserInput) (models.UserAvatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserAvatar", arg0)
	ret0, _ := ret[0].(models.UserAvatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserAvatar indicates an expected call of GetUserAvatar
func (mr *MockUserStorageMockRecorder) GetUserAvatar(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserAvatar", reflect.TypeOf((*MockUserStorage)(nil).GetUserAvatar), arg0)
}

// GetUserProfile mocks base method
func (m *MockUserStorage) GetUserProfile(arg0 models.UserInput) (models.UserOutside, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserProfile", arg0)
	ret0, _ := ret[0].(models.UserOutside)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserProfile indicates an expected call of GetUserProfile
func (mr *MockUserStorageMockRecorder) GetUserProfile(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserProfile", reflect.TypeOf((*MockUserStorage)(nil).GetUserProfile), arg0)
}
